import uuid from "react-native-uuid";
function BoatForm() {
  const inputFields = [
    {
      id: uuid.v4(),
      title: "Yacht Name",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "USCG or other documentation number",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "2593cac3-2583-4f54-93d3-d8a5ff6633a7",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Yacht Make and Model",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "1a0d447d-3985-4866-acdf-fffe7cfe3a05",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Yacht Length",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "37be27a0-4be9-4031-b786-8130b3c07698",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Type of Yacht",
      type: "radio",
      options: [
        { optionsId: "", optionName: "None", id: uuid.v4() },
        { optionsId: "", optionName: "Monohull", id: uuid.v4() },
        { optionsId: "", optionName: "Multihull", id: uuid.v4() },
      ],
      customAttributeId: "7d5cbd20-30c5-4628-8c88-7c8ccecd63ed",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Color, hull material and prominent features",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "8d47e9e8-3bef-4797-acae-43d8a2dadb5e",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Enter the Motoring Range of your boat in nautical miles",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "0e7d55a7-6d10-471a-a0c7-ee2be10168a0",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Which communication devices will you have on your boat",
      type: "checkbox",
      options: [
        { optionsId: "", optionName: "SSB (receive only)", id: uuid.v4() },
        {
          optionsId: "",
          optionName: "SSB (Transmit and Receive)",
          id: uuid.v4(),
        },
        {
          optionsId: "",
          optionName: "Starlink (or other high speed internet service)",
          id: uuid.v4(),
        },
        {
          optionsId: "",
          optionName: "Sat Phone/ Sat based system (like Skymate)",
          id: uuid.v4(),
        },
        { optionsId: "", optionName: "Iridium Go!", id: uuid.v4() },
        { optionsId: "", optionName: "Iridium Extreme", id: uuid.v4() },
        { optionsId: "", optionName: "InReach", id: uuid.v4() },
        { optionsId: "", optionName: "SPOT", id: uuid.v4() },
        { optionsId: "", optionName: "SPOT X", id: uuid.v4() },
        { optionsId: "", optionName: "Zoleo", id: uuid.v4() },
        { optionsId: "", optionName: "Bivy", id: uuid.v4() },
        { optionsId: "", optionName: "YellowBrick", id: uuid.v4() },
        { optionsId: "", optionName: "Other", id: uuid.v4() },
        { optionsId: "", optionName: "None", id: uuid.v4() },
      ],
      customAttributeId: "497f1b8f-22a5-477f-b815-1bbb6e312ce8",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title:
        "Which communication device will you use to send position reports to the tracking map?",
      type: "radio",
      options: [
        { optionsId: "", optionName: "InReach", id: uuid.v4() },
        { optionsId: "", optionName: "Zoleo", id: uuid.v4() },
        {
          optionsId: "",
          optionName: "Other (Follow up Required)",
          id: uuid.v4(),
        },
        { optionsId: "", optionName: "None", id: uuid.v4() },
      ],
      customAttributeId: "70414622-2c4f-4993-8744-abd764a8db34",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Tracking Device Shared Page (inReach)",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "cac3ab58-43bb-4014-b3ea-4a63bf01518b",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Tracking Device Shared Page (SPOT, SPOT X)",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "4cfb97e0-cd67-4e13-a26e-d9502ca08825",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "IMEI (required for Zoleo, inReach)",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "799ee9cd-6630-42f2-ad97-f474739fdd0f",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "InReach Email Address",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "1526a07f-028e-47c5-b1ff-f9bc7e8ecf22",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Do you have a PredictWind account?",
      type: "radio",
      options: [
        { optionsId: "", optionName: "No", id: uuid.v4() },
        { optionsId: "", optionName: "Yes", id: uuid.v4() },
      ],
      customAttributeId: "887912c4-5808-4e56-aeb1-0317d4801947",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "What email address do you use with the PredictWind account",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "ff6e18cc-a956-4c86-aa23-dc07e376aecc",
      isVisible: false,
    },
    {
      id: uuid.v4(),
      title: "PredictWind Tracking Page url",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "cec10be5-5832-4273-a6e0-4d11b01e43eb",
      isVisible: false,
    },
    {
      id: uuid.v4(),
      title: "Sat Phone number",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "efeecaf7-c99a-4b6f-b1a1-a07b347d1345",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Which devices will you use to send/receive email offshore?",
      type: "checkbox",
      options: [
        { optionsId: "", optionName: "SSB (Pactor Modem)", id: uuid.v4() },
        {
          optionsId: "",
          optionName: "Sat Phone/ Sat based system (like Skymate)",
          id: uuid.v4(),
        },
        {
          optionsId: "",
          optionName: "Starlink or other high speed internet system",
          id: uuid.v4(),
        },
        {
          optionsId: "",
          optionName: "Iridium Go! or Iridium Extreme",
          id: uuid.v4(),
        },
        { optionsId: "", optionName: "Other", id: uuid.v4() },
        {
          optionsId: "",
          optionName: "I don't have access to email offshore",
          id: uuid.v4(),
        },
      ],
      customAttributeId: "6f6ee3f0-6ded-44e8-8de2-d511a4abe399",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Offshore email",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "3121c513-05e4-4200-9c66-e045f2acf1dd",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Other comms and safety equipment on board",
      type: "checkbox",
      options: [
        { optionsId: "", optionName: "Fixed Mount VHF", id: uuid.v4() },
        { optionsId: "", optionName: "Handheld VHF", id: uuid.v4() },
        { optionsId: "", optionName: "EPIRB", id: uuid.v4() },
        { optionsId: "", optionName: "PLB", id: uuid.v4() },
        { optionsId: "", optionName: "AIS (Receive only)", id: uuid.v4() },
        {
          optionsId: "",
          optionName: "AIS (Transmit and Receive)",
          id: uuid.v4(),
        },
        { optionsId: "", optionName: "Radar", id: uuid.v4() },
      ],
      customAttributeId: "216d180b-50fd-418a-bab7-a2c6b7a9fb36",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "EPIRB numbers",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "66e899a7-58fe-424d-978e-c01d36af21bb",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "MMSI",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "fc0ae0e6-5c77-4548-bb1c-5194149ffe3c",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Life raft Manufacturer, Model and Capacity",
      type: "text",
      options: [{ optionsId: "", optionName: "", id: uuid.v4() }],
      customAttributeId: "d9812798-401a-4a13-82b5-45fc74e09eeb",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Do you have Children onboard?",
      type: "radio",
      options: [
        { optionsId: "", optionName: "None", id: uuid.v4() },
        { optionsId: "", optionName: "No", id: uuid.v4() },
        { optionsId: "", optionName: "Yes", id: uuid.v4() },
      ],
      customAttributeId: "34dfbe52-e6eb-487a-bb40-657c995c8f75",
      isVisible: true,
    },
    {
      id: uuid.v4(),
      title: "Do you have pets aboard?",
      type: "checkbox",
      options: [
        { optionsId: "", optionName: "Cat", id: uuid.v4() },
        { optionsId: "", optionName: "Dog", id: uuid.v4() },
        { optionsId: "", optionName: "Other", id: uuid.v4() },
        { optionsId: "", optionName: "None", id: uuid.v4() },
      ],
      customAttributeId: "077d4bad-7ab3-4bef-a332-a265923dd157",
      isVisible: true,
    },
  ];
  return inputFields;
}
export { BoatForm };
